name: CI-Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  knowledge:
    runs-on: ubuntu-latest
    env:
      FAKE_SECRET_TOKEN: 4834bcb4e460a0d3605695e3b6bc415d3020785e888b656824cf1b54a54943c4bcb2355d
      DEPLOY_ENV: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Echo Fake Token
      run: echo "Using token: $FAKE_SECRET_TOKEN"

    - name: Deploy to production
      run: echo "Deploying to production with token $FAKE_SECRET_TOKEN"
